config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
  	resources :comments
  end
  #article GET    /articles/:id(.:format)      articles#show
root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	 has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	validates :title, :content, :category_id, presence: true
	has_many :line_items, inverse_of: :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
  	@article = Article.new
	end
 
	def edit
  	@article = Article.find(params[:id])
	end
#set your own name and password
	http_basic_authenticate_with name: "user", password: "password", except: [:index, :show]

	def index
    @articles = Article.all
  	end

	def show
		@article = Article.find(params[:id])
	end 

	def create
		 @article = Article.new(params.require(:article).permit(:title, :text))
 
  		 if @article.save
    	redirect_to @article
  		else
    	render 'new'
  		end
	end

	def update
  		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
    	redirect_to @article
  		else
    	render 'edit'
  		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end 

private
  	def article_params
    params.require(:article).permit(:title, :text)
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "user", password: "password", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
		if params[:category].blank?
  		@posts = Post.all.order("created_at DESC")
  		else
  		@category_id = Category.find_by(name: params[:category]).id
  		@posts = Post.where(category_id: @category_id).order("created_at DESC")
  		end
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post, notice: "This post was created!"
		else
			render 'new'
		end 
	end

	def edit
	end

	def update
		if @post.update(post_params)
          redirect_to @post, notice: "Update successful"
     else
          render 'edit'
     end
	end

	def destroy
		@post.destroy
		redirect_to root_pat, notice: "Post destroyed!"
	end

private 

	def post_params
		 params.require(:post).permit(:title, :content, :category_id)
	end

	def find_post
		@post = Post.find(params[:id])
	end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>
<h2>This is a personal blog.</h2>
<%= link_to 'My Blog', controller: 'articles' %>

 <%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %><td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
     <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Choose a category" }) %><br>
     <%= f.label :title %><br>
     <%= f.text_field :title, placeholder: "Type the post title here" %><br>
     <%= f.label :content %><br>
     <%= f.text_area :content, size: "60x12", placeholder: "Type the post tect here" %><br>
 
     <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to “Back”, root_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<h1><%= link_to "post.title", post %></h1>
	<p><%= post.content %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" %>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
     <div>
          <p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</p>
          <ul>
               <% @post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
               <% end %>
          </ul> 
     </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>